DROP TABLE DIM_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE DIM_STORE CASCADE CONSTRAINTS;
DROP TABLE DIM_SUPPLIER CASCADE CONSTRAINTS;
DROP TABLE DIM_TIME CASCADE CONSTRAINTS;
DROP TABLE SALESFACT CASCADE CONSTRAINTS;


CREATE TABLE DIM_PRODUCT(
PRODUCT_ID VARCHAR2(6) NOT NULL,
PRODUCT_NAME VARCHAR2(30) NOT NULL,
PRICE NUMBER(5,2) NOT NULL
);
ALTER TABLE DIM_PRODUCT ADD CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_ID);

COMMIT;

CREATE TABLE DIM_CUSTOMER(
CUSTOMER_ID VARCHAR2(4) NOT NULL,
CUSTOMER_NAME VARCHAR2(30) NOT NULL
);
ALTER TABLE DIM_CUSTOMER ADD CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_ID);

COMMIT;

CREATE TABLE DIM_STORE(
STORE_ID VARCHAR2(4) NOT NULL,
STORE_NAME VARCHAR2(20) NOT NULL
);
ALTER TABLE DIM_STORE ADD CONSTRAINT PK_DIM_STORE PRIMARY KEY (STORE_ID);

COMMIT;

CREATE TABLE DIM_SUPPLIER(
SUPPLIER_ID VARCHAR2(5) NOT NULL,
SUPPLIER_NAME VARCHAR2(30) NOT NULL
);
ALTER TABLE DIM_SUPPLIER ADD CONSTRAINT PK_DIM_SUPPLIER PRIMARY KEY (SUPPLIER_ID);

COMMIT;

CREATE TABLE DIM_TIME AS 
(SELECT
    'T-' || N AS TIME_ID,
    TO_DATE('31/12/2018', 'DD/MM/YYYY') + NUMTODSINTERVAL(N, 'DAY') AS FULL_DATE,
    TO_CHAR(TO_DATE('31/12/2018', 'DD/MM/YYYY') + NUMTODSINTERVAL(N, 'DAY'), 'DAY') AS COL_DAY,
    TO_CHAR(TO_DATE('31/12/2018', 'DD/MM/YYYY') + NUMTODSINTERVAL(N, 'DAY'), 'WW') AS COL_WEEK,
    EXTRACT(MONTH FROM TO_DATE('31/12/2018', 'DD/MM/YYYY') + NUMTODSINTERVAL(N, 'DAY')) AS COL_MONTH,
    TRIM(TO_CHAR(TO_DATE('31/12/2018', 'DD/MM/YYYY') + NUMTODSINTERVAL(N, 'DAY'), 'Q')) AS COL_QUARTER,
    TRIM(TO_CHAR(TO_DATE('31/12/2018', 'DD/MM/YYYY') + NUMTODSINTERVAL(N, 'DAY'), 'YYYY')) AS COL_YEAR
FROM (SELECT LEVEL N FROM DUAL CONNECT BY LEVEL <= 365)
);
ALTER TABLE DIM_TIME ADD CONSTRAINT PK_DIM_TIME PRIMARY KEY (TIME_ID);

COMMIT;


CREATE TABLE SALESFACT(
TRANSACTIONS_ID VARCHAR2(8) NOT NULL,
PRODUCT_ID VARCHAR2(6) NOT NULL,
CUSTOMER_ID VARCHAR2(4) NOT NULL,
STORE_ID VARCHAR2(4) NOT NULL,
QUANTITY NUMBER(3,0) NOT NULL,
SUPPLIER_ID VARCHAR2(5) NOT NULL,
TIME_ID VARCHAR2(42) NOT NULL,
TOTAL_SALE NUMBER(10,2) NOT NULL
);
ALTER TABLE SALESFACT ADD CONSTRAINT PK_SALESFACT PRIMARY KEY (TRANSACTIONS_ID);
ALTER TABLE SALESFACT ADD CONSTRAINT FK_SALESFACT_DIM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID);
ALTER TABLE SALESFACT ADD CONSTRAINT FK_SALESFACT_DIM_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID);
ALTER TABLE SALESFACT ADD CONSTRAINT FK_SALESFACT_DIM_STORE FOREIGN KEY (STORE_ID) REFERENCES DIM_STORE(STORE_ID);
ALTER TABLE SALESFACT ADD CONSTRAINT FK_SALESFACT_DIM_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES DIM_SUPPLIER(SUPPLIER_ID);
ALTER TABLE SALESFACT ADD CONSTRAINT FK_SALESFACT_DIM_TIME FOREIGN KEY (TIME_ID) REFERENCES DIM_TIME(TIME_ID);

COMMIT;