create or replace PROCEDURE INLJ 
IS 
BEGIN

DECLARE
    N_PRODUCT_NAME MASTERDATA.PRODUCT_NAME%TYPE;
    N_SUPPLIER_ID   MASTERDATA.SUPPLIER_ID%TYPE;
    N_SUPPLIER_NAME MASTERDATA.SUPPLIER_NAME%TYPE;
    N_PRICE MASTERDATA.PRICE%TYPE;
    TRANS_TIME_ID VARCHAR2(42);
    TYPE TRANSLIST IS TABLE OF TRANSACTIONS%ROWTYPE;
    TRANS_RECORDS TRANSLIST;
    ROW_NUM NUMBER;
    CURSOR TRANS_CUR IS 
        SELECT * FROM TRANSACTIONS ORDER BY TRANSACTIONS_ID;
BEGIN
    OPEN TRANS_CUR; 

    LOOP
        FETCH TRANS_CUR BULK COLLECT INTO TRANS_RECORDS LIMIT 50;
        EXIT WHEN TRANS_CUR%NOTFOUND;

        FOR INDX IN TRANS_RECORDS.FIRST .. TRANS_RECORDS.LAST LOOP
            SELECT PRODUCT_NAME, SUPPLIER_ID, SUPPLIER_NAME, PRICE INTO N_PRODUCT_NAME, N_SUPPLIER_ID, N_SUPPLIER_NAME, N_PRICE
            FROM MASTERDATA 
            WHERE PRODUCT_ID = TRANS_RECORDS(INDX).PRODUCT_ID;

            --CHECK IF THIS RECORD EXISTS IN DIM_PRODUCT
            SELECT COUNT(*) INTO ROW_NUM FROM DIM_PRODUCT WHERE PRODUCT_ID = TRANS_RECORDS(INDX).PRODUCT_ID;
            IF ROW_NUM = 0 THEN
            --INSERT THIS RECORD INTO DIM_PRODUCT
            INSERT INTO DIM_PRODUCT VALUES(TRANS_RECORDS(INDX).PRODUCT_ID, N_PRODUCT_NAME, N_PRICE);
            COMMIT;
            END IF;

            --CHECK IF THIS RECORD EXISTS IN DIM_CUSTOMER
            SELECT COUNT(*) INTO ROW_NUM FROM DIM_CUSTOMER WHERE CUSTOMER_ID = TRANS_RECORDS(INDX).CUSTOMER_ID;
            IF ROW_NUM = 0 THEN
            --INSERT THIS RECORD INTO DIM_CUSTOMER
            INSERT INTO DIM_CUSTOMER VALUES(TRANS_RECORDS(INDX).CUSTOMER_ID, TRANS_RECORDS(INDX).CUSTOMER_NAME);
            COMMIT;
            END IF;

            --CHECK IF THIS RECORD EXISTS IN DIM_STORE
            SELECT COUNT(*) INTO ROW_NUM FROM DIM_STORE WHERE STORE_ID = TRANS_RECORDS(INDX).STORE_ID;
            IF ROW_NUM = 0 THEN
            --INSERT THIS RECORD INTO DIM_STORE
            INSERT INTO DIM_STORE VALUES(TRANS_RECORDS(INDX).STORE_ID, TRANS_RECORDS(INDX).STORE_NAME);
            COMMIT;
            END IF;

            --CHECK IF THIS RECORD EXISTS IN DIM_SUPPLIER
            SELECT COUNT(*) INTO ROW_NUM FROM DIM_SUPPLIER WHERE SUPPLIER_ID = N_SUPPLIER_ID;
            IF ROW_NUM = 0 THEN
            --INSERT THIS RECORD INTO DIM_SUPPLIER
            INSERT INTO DIM_SUPPLIER VALUES(N_SUPPLIER_ID, N_SUPPLIER_NAME);
            COMMIT;
            END IF;

            --CHECK IF THIS RECORD EXISTS IN SALESFACT
            SELECT TIME_ID INTO TRANS_TIME_ID FROM DIM_TIME WHERE FULL_DATE = TRANS_RECORDS(INDX).T_DATE;
            SELECT COUNT(*) INTO ROW_NUM FROM SALESFACT WHERE TRANSACTIONS_ID = TRANS_RECORDS(INDX).TRANSACTIONS_ID;
            IF ROW_NUM = 0 THEN
            --INSERT THIS RECORD INTO SALESFACT
            INSERT INTO SALESFACT VALUES(TRANS_RECORDS(INDX).TRANSACTIONS_ID, TRANS_RECORDS(INDX).PRODUCT_ID,
                                        TRANS_RECORDS(INDX).CUSTOMER_ID, TRANS_RECORDS(INDX).STORE_ID, 
                                        TRANS_RECORDS(INDX).QUANTITY, N_SUPPLIER_ID, TRANS_TIME_ID,
                                        TRANS_RECORDS(INDX).QUANTITY * N_PRICE);
            COMMIT;
            END IF;

        END LOOP;
    END LOOP;

END;

END INLJ;